### ISSUE TITLE
[BUG]: postgresql:// should be a valid connection string protocol

### ISSUE THREAD

**Issue by EdgarPost** [anza-labs/charts#160]
### What happened?

It could be in a different setup of course, but when using CloudNativePG in combination with FluxCD, eg:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: auth
spec:
  interval: 10m
  chart:
    spec:
      chart: pocket-id
      version: 1.1.5
      sourceRef:
        kind: HelmRepository
        name: anza-labs
        namespace: auth
      interval: 10m
  values:
    database:
      provider: postgres
  valuesFrom:
    - kind: Secret
      name: pocket-id-app
      targetPath: database.connectionString
      valuesKey: uri
```

You receive the following error:
```
Helm install failed for release auth/pocket-id with chart pocket-id@1.1.5: execution error at (pocket-id/templates/secret.yaml:6:8): Invalid database connectionString
: postgresql://app:ZOE....5skyKzXG5@pocket-id-rw.auth:5432/app. .Values.database.connectionString must start with 'postgres://' when .Values.database.provider is 'postgres'.
```

According to the [Connection URIs spec](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING), `postgresql://` should be valid as well.

> The URI scheme designator can be either postgresql:// or postgres://. 

### Relevant log output

```Text

```
